from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime
from app.database import Base


class WordSet(Base):
    """A set of words containing the main word and its distractors (similar, synonym, antonym)"""
    __tablename__ = "word_sets"

    id = Column(Integer, primary_key=True, index=True)
    main_word = Column(String(100), nullable=False, index=True)  # Word A
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationship to words
    words = relationship("Word", back_populates="word_set", cascade="all, delete-orphan")


class Word(Base):
    """Individual word with its type (main, similar, synonym, antonym) and image"""
    __tablename__ = "words"

    id = Column(Integer, primary_key=True, index=True)
    word_set_id = Column(Integer, ForeignKey("word_sets.id"), nullable=False)
    word = Column(String(100), nullable=False)
    word_type = Column(String(20), nullable=False)  # 'main', 'similar', 'synonym', 'antonym'
    meaning = Column(String(500), nullable=True)  # Chinese meaning of the word
    image_prompt = Column(Text, nullable=True)
    image_url = Column(String(500), nullable=True)
    image_local_path = Column(String(500), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationship to word set
    word_set = relationship("WordSet", back_populates="words")


class ClozeTest(Base):
    """Cloze test exercise with two words"""
    __tablename__ = "cloze_tests"

    id = Column(Integer, primary_key=True, index=True)
    word1 = Column(String(100), nullable=False)  # First word
    word2 = Column(String(100), nullable=False)  # Second word
    word1_meaning = Column(String(500), nullable=True)  # Chinese meaning of word1
    word2_meaning = Column(String(500), nullable=True)  # Chinese meaning of word2
    sentence = Column(Text, nullable=False)  # Chinese sentence with blanks
    sentence_with_answers = Column(Text, nullable=False)  # Sentence with words filled in
    image_prompt = Column(Text, nullable=True)  # Image generation prompt
    image_url = Column(String(500), nullable=True)
    image_local_path = Column(String(500), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class ListeningExercise(Base):
    """Listening exercise with scene description"""
    __tablename__ = "listening_exercises"

    id = Column(Integer, primary_key=True, index=True)
    scene_description = Column(Text, nullable=False)  # User's scene description
    generated_text = Column(Text, nullable=True)  # Text generated by LLM for TTS
    image_prompt = Column(Text, nullable=True)  # Image generation prompt
    image_url = Column(String(500), nullable=True)
    image_local_path = Column(String(500), nullable=True)
    audio_url = Column(String(500), nullable=True)  # TTS audio URL
    audio_local_path = Column(String(500), nullable=True)  # Local audio file path
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
